--by Diego Bosca 20210521
INSERT INTO procedure_occurrence
(
    procedure_occurrence_id, -- autogenerated
    person_id,
    procedure_concept_id,
    procedure_date, -- date?
    procedure_datetime,
    procedure_type_concept_id, -- Record as primary procedure (44786630) 
    modifier_concept_id,
    quantity,
    provider_id,
    visit_occurrence_id,
    visit_detail_id,
    procedure_source_value,
    procedure_source_concept_id,
    modifier_source_value
)
SELECT
 -- [MAPPING COMMENT] no mapping logic defined. Put NULL
    nextval('procedure_id_seq') AS procedure_occurrence_id,

    i2b2_procedure.patient_num AS person_id,

 -- [MAPPING   LOGIC] Only populate for records where concept_cd starts with ES_12OCTUBRE_PROC or ICD10PCS  Codes with ICD10PCS are normally standard codes in OMOP and should not be mapped further  For ES_12OCTUBRE_PROC codes, join to concept_dimension and retrieve concept_path (last portion mapping to the ICD10PCS code and take this ton retrieve standard concept_id)  
    COALESCE((SELECT TARGET_CONCEPT_ID FROM source_to_concept_map WHERE SOURCE_CODE=concept_cd AND INVALID_REASON IS NULL limit 1),0) 
	AS procedure_concept_id,

	i2b2_procedure.start_date::date AS procedure_date,

 -- [MAPPING COMMENT] no mapping logic defined. Put NULL
    i2b2_procedure.start_date AS procedure_datetime,

 -- [Fixed to] Record as primary procedure (44786630) 
    44786630 AS procedure_type_concept_id,

 -- [MAPPING COMMENT] no mapping logic defined. Put NULL
    NULL AS modifier_concept_id,

 -- [MAPPING COMMENT] no mapping logic defined. Put NULL
    NULL AS quantity,

	split_part(i2b2_procedure.provider_id, ':', 2)::INTEGER AS provider_id,

    i2b2_procedure.encounter_num AS visit_occurrence_id,

 -- [MAPPING COMMENT] no mapping logic defined. Put NULL
    NULL AS visit_detail_id,

    i2b2_procedure.concept_cd AS procedure_source_value,

 -- [MAPPING COMMENT] no mapping logic defined. Put NULL
 	CASE
		WHEN i2b2_procedure.concept_cd LIKE 'ICD10PCS%' THEN COALESCE((SELECT SOURCE_CONCEPT_ID FROM source_to_concept_map WHERE SOURCE_CODE=concept_cd AND INVALID_REASON IS NULL limit 1),0) 
		ELSE 0
	END AS procedure_source_concept_id,
   
 -- [MAPPING COMMENT] no mapping logic defined. Put NULL
    NULL AS modifier_source_value

--i2b2_procedure is i2b2.observation_fact where concept_cd is ES_12OCTUBRE_PROC or ICD10PCS 
FROM i2b2_procedure;